[package]
name = "LogicalCompilerVerification"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "13bf7613c96a9fd66a81b9020a82cad9a6ea1fcf"}
